version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-node:
    executor: node/default
    working_directory: ~/project/ATA-FRONT-END
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      
      # New step: Check commit message format
      - run:
          name: Check commit message format
          command: |
            #!/bin/bash
            set -e
            # Get the commit message
            COMMIT_MSG=$(git log -1 --pretty=%B)
            # Define the allowed prefixes
            ALLOWED_PREFIXES="Add:|Refactor:|Fix:|Feat:|Docs:|Style:|Test:|Chore:"
            # Check if the commit message starts with an allowed prefix
            if ! echo "$COMMIT_MSG" | grep -qE "^($ALLOWED_PREFIXES)"; then
              echo "Error: Commit message must start with one of: $ALLOWED_PREFIXES"
              exit 1
            fi
            # Check if the commit message is at least 10 characters long
            if [ ${#COMMIT_MSG} -lt 10 ]; then
              echo "Error: Commit message must be at least 10 characters long"
              exit 1
            fi
            # Check if the commit message has a body (separated by a blank line)
            if ! echo "$COMMIT_MSG" | grep -q "^$"; then
              echo "Error: Commit message must have a body separated by a blank line"
              exit 1
            fi
            echo "Commit message format is valid!"
      
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

workflows:
  build:
    jobs:
      - build-node
